version: '3.8'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: burger_orderer
      MYSQL_USER: senai-amn
      MYSQL_PASSWORD: your_password
    volumes:
      - ./db_data:/var/lib/mysql  # Persisting database data
      - ./sql/burger_orderer/setup.sql:/docker-entrypoint-initdb.d/setup.sql  # Additional setup SQL
      - ./sql/burger_orderer/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql  # Additional setup SQL
      - ./sql/burger_orderer/insert.sql:/docker-entrypoint-initdb.d/insert.sql  # Additional setup SQL
    ports:
      - "3306:3306"  # Exposing MariaDB's port for external connections
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
