version: '3.9'
services:
  mariadb:
    image: mariadb:11.5.2
    container_name: burger_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: senai-amn
      MYSQL_PASSWORD: your_password
      MYSQL_DATABASE: burger_orderer
    ports:
      - "3306:3306"
    volumes:
      - ./sql/burger_orderer/reset.sql:/docker-entrypoint-initdb.d/reset.sql
      - ./sql/burger_orderer:/mariadb-scripts
    command: ['mariadbd', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  kitchen:
    build:
      context: .
    container_name: kitchen_service
    environment:
      NODE_ENV: docker
      DB_HOST: mariadb
      DB_USER: senai-amn
      DB_PASSWORD: your_password
      DB_NAME: burger_orderer
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    command: ["node", "./kitchen.js"]

  menu:
    build:
      context: .
    container_name: menu_service
    environment:
      NODE_ENV: docker
      DB_HOST: mariadb
      DB_USER: senai-amn
      DB_PASSWORD: your_password
      DB_NAME: burger_orderer
    ports:
      - "4000:4000"
    depends_on:
      - mariadb
    command: ["node", "./menu.js"]
